baseURL = 'https://rejowan.com/GitBlog'
languageCode = 'en-us'
title = 'K M Rejowan Ahmmed'
theme = 'github-style-plus'
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
    author = "K M Rejowan Ahmmed"
    description = "Seeking Simplicity in Complexity"
    github = "ahmmedrejowan"
    enableGithubFollowers = true
    twitter = "ahmmedrejowan"
    linkedin = "ahmmedrejowan"
    email = "kmrejowan@gmail.com"
    stackoverflow="9932194"
    lastmod = true
    userStatusEmoji = "ðŸ˜‰"
    favicon = "/images/avatar.png"
    avatar = "/images/avatar.png"
    location = "Dhaka, Bangladesh"
    enableGitalk = true
    rss = true
    enableLocalSearch = true
    sponsorLink = "https://www.linkedin.com/in/ahmmedrejowan/"
    customStyleFile = "your css file name"
    gtmId = "your gtm id"

#    [[params.links]]
#        title = "GitHub"
#        href = "https://github.com/ahmmedrejowan"
#
#    [[params.links]]
#        title = "LinkedIn"
#        href = "https://www.linkedin.com/in/ahmmedrejowan/"
#
#    [[params.links]]
#        title = "Twitter"
#        href = "https://twitter.com/ahmmedrejowan"
#
#    [[params.links]]
#        title = "Stack Overflow"
#        href = "https://stackoverflow.com/users/9932194/"

